# Generated by Django 6.0.4 on 2026-05-18 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_agentdevice'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentdevice',
            name='comment_detection_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='agentdevice',
            name='predefined_reply',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agentdevice',
            name='reply_mode',
            field=models.CharField(choices=[('ai', 'AI'), ('predefined', 'Predefined')], default='ai', max_length=20),
        ),
    ]
