# Generated by Django 6.0.4 on 2026-05-18 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_agentdevice_comment_detection_enabled_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentdevice',
            name='comment_detection_enabled',
        ),
        migrations.RemoveField(
            model_name='agentdevice',
            name='predefined_reply',
        ),
        migrations.RemoveField(
            model_name='agentdevice',
            name='reply_mode',
        ),
    ]
