"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure--0kgpz)11o%f4w+1d@tz7u)n5smiz(g)6r0had9nof7%!d-5*f'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]

AUTH_USER_MODEL = 'accounts.User'
# Application definition

INSTALLED_APPS = [
    'daphne',
    'channels',

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'apps.accounts',
    'apps.posts',
    'apps.comments',
    'apps.scheduler',
    'apps.content_plans',
    'django_celery_beat',
    'corsheaders',
]

# <<<<<<< Updated upstream
# ---------------------------------------------------------------------------
# Content Plans / AI Image Generation
# ---------------------------------------------------------------------------
import os

# 32-byte url-safe base64 Fernet key used to encrypt user-supplied AI API keys.
# In production set AI_KEY_FERNET_KEY in the environment. For local dev we fall
# back to a key derived from SECRET_KEY (NOT safe for production rotation).
AI_KEY_FERNET_KEY = os.environ.get("AI_KEY_FERNET_KEY", "")

# Gemini configuration
GEMINI_IMAGE_MODEL = os.environ.get("GEMINI_IMAGE_MODEL", "gemini-2.5-flash-image")
GEMINI_VIDEO_MODEL = os.environ.get("GEMINI_VIDEO_MODEL", "veo-3.0-fast-generate-001")
GEMINI_TEXT_MODEL = os.environ.get("GEMINI_TEXT_MODEL", "gemini-2.5-flash")
GEMINI_REQUEST_TIMEOUT = 60
# How often (seconds) to poll a Veo long-running operation, and the overall
# timeout before we give up.
GEMINI_VIDEO_POLL_INTERVAL = int(os.environ.get("GEMINI_VIDEO_POLL_INTERVAL", "10"))
GEMINI_VIDEO_TIMEOUT = int(os.environ.get("GEMINI_VIDEO_TIMEOUT", "600"))

# Content plan limits / quotas
CONTENT_PLAN_MAX_REGENS = 3
CONTENT_PLAN_MAX_DURATION_DAYS = 30
CONTENT_PLAN_MIN_DURATION_DAYS = 1
CONTENT_PLAN_SCRAPE_TIMEOUT = 10
CONTENT_PLAN_IMAGE_CONCURRENCY = 3

CELERY_BROKER_URL = "redis://127.0.0.1:6379/8"
CELERY_RESULT_BACKEND = "redis://127.0.0.1:6379/9"
# =======
# CELERY_BROKER_URL = "redis://127.0.0.1:6379/8"
# CELERY_RESULT_BACKEND = "redis://127.0.0.1:6379/9"
# >>>>>>> Stashed changes

# CELERY_BROKER_URL = "redis://127.0.0.1:6379/0"
# CELERY_RESULT_BACKEND = "redis://127.0.0.1:6379/0"

CELERY_TIMEZONE = "Asia/Kolkata"
CELERY_ENABLE_UTC = False

CELERY_BEAT_SCHEDULE = {
    "check-scheduled-posts-every-minute": {
        "task": "apps.scheduler.tasks.check_scheduled_posts",
        "schedule": 60.0,
    },
}

ASGI_APPLICATION = "config.asgi.application"

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [("127.0.0.1", 6379)],
        },
    },
}

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',

    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',  # kept for Django admin
    'django.middleware.common.CommonMiddleware',
    # CsrfViewMiddleware removed — APIs use stateless JWT auth
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# SITE_BASE_URL = "http://127.0.0.1:8000"

SITE_BASE_URL = "https://agents.zettalgor.com"

CORS_ALLOW_ALL_ORIGINS = True

CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "https://agents.zettalgor.com",
]

CSRF_TRUSTED_ORIGINS = [
    "http://localhost:8000",
    "http://localhost:3000",
    "https://agents.zettalgor.com",
]

ZETTALGOR_API_URL = "https://api.zettalgor.com/v1/chat/completions"
ZETTALGOR_API_KEY = "ze_al_FPY-bLcxsG2gh6uWee6KLP8JXVYk5F759Ubu7FDm25k"
ZETTALGOR_MODEL = "ZAi8"

# ---------------------------------------------------------------------------
# Django REST Framework — JWT-only authentication
# ---------------------------------------------------------------------------
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
}

from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=30),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': False,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
}

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'zetta_social',
        'USER': 'postgres',
        'PASSWORD': 'admin',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"