# Generated by Django 6.0.4 on 2026-05-07 12:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0002_remove_post_created_at_postmedia'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PostComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=50)),
                ('comment_author', models.CharField(blank=True, max_length=255, null=True)),
                ('comment_text', models.TextField()),
                ('comment_hash', models.CharField(max_length=255, unique=True)),
                ('reply_type', models.CharField(choices=[('predefined', 'Predefined'), ('ai', 'AI')], default='predefined', max_length=20)),
                ('reply_text', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('reply_pending', 'Reply Pending'), ('reply_sent', 'Reply Sent'), ('reply_failed', 'Reply Failed')], default='new', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('replied_at', models.DateTimeField(blank=True, null=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='posts.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
