# Generated by Django 6.0.2 on 2026-05-13 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcomment',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('reply_pending', 'Reply Pending'), ('reply_sent', 'Reply Sent'), ('reply_failed', 'Reply Failed'), ('ignored', 'Ignored')], default='new', max_length=30),
        ),
    ]
