# Generated by Django 6.0.2 on 2026-05-13 08:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_alter_postcomment_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('AI', 'AI Mode'), ('MANUAL', 'Manual Mode')], default='AI', max_length=10)),
                ('tone', models.CharField(choices=[('friendly', 'Friendly'), ('professional', 'Professional'), ('casual', 'Casual')], default='friendly', max_length=20)),
                ('keyword_replies', models.JSONField(blank=True, default=dict, help_text='JSON mapping of keywords to replies')),
                ('default_reply', models.TextField(blank=True, default='Thank you for your comment!')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='comment_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
