# Generated by Django 6.0.4 on 2026-05-15 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_commentsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentsettings',
            name='is_comment_detection_on',
            field=models.BooleanField(default=True, help_text='If enabled, it runs comment detection; otherwise, it runs normal posting code.'),
        ),
    ]
