# Generated by Django 6.0.4 on 2026-05-15 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0004_commentsettings_is_comment_detection_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentsettings',
            name='is_comment_detection_on',
            field=models.BooleanField(default=True, help_text='If enabled, it runs comment detection.'),
        ),
    ]
