# Generated by Django 6.0.4 on 2026-05-21 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0008_alter_postcomment_post_delete_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcomment',
            name='comment_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
