# Generated by Django 6.0.4 on 2026-05-08 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_remove_post_created_at_postmedia'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
