# Generated by Django 6.0.4 on 2026-05-18 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_post_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comment_detection',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='predefined_reply_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='reply_mode',
            field=models.CharField(choices=[('ai', 'AI Reply'), ('predefined', 'Predefined Reply'), ('none', 'No Reply')], default='none', max_length=20),
        ),
    ]
