# Generated by Django 6.0.4 on 2026-05-18 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_comment_detection_post_predefined_reply_message_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='comment_detection',
        ),
        migrations.RemoveField(
            model_name='post',
            name='predefined_reply_message',
        ),
        migrations.RemoveField(
            model_name='post',
            name='reply_mode',
        ),
        migrations.AddField(
            model_name='post',
            name='last_comment_check',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='platform_post_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
