# Generated by Django 6.0.4 on 2026-05-18 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_remove_post_comment_detection_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='last_comment_check',
        ),
        migrations.RemoveField(
            model_name='post',
            name='platform_post_id',
        ),
    ]
