# Generated by Django 6.0.4 on 2026-05-18 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_remove_post_last_comment_check_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='platform_post_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
