# Generated by Django 6.0.4 on 2026-05-19 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_post_error_message_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
